### ISSUE TITLE
text size/color and readability

### ISSUE THREAD

**Issue by misterrodger** [facn5/EZSearch#21]
white text on grass background is a bit tricky to read, maybe put dark drop shadow effect on the text?

the search field is a bit narrow on small mobile phones.  when it expands it is good, maybe make the initial size a bit wider?  

text inside the search text field is a bit small and not easy for everyone to read

otherwise great job.  fun and functional site.

**Comment by ghost** [comment]
The background is changed, the white goes what the current background we currently have, the text-field is supposed to be small initally, and it's easy clickable to expand.
